# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thoughts and Stuff
author: Karan Varindani
email: karan301@me.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and Stuff is a place for me to get my thoughts about Apple and tech in general out of my head. Occasionally, I might write about travel, education, or football, too. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thoughtsandstuff.net" # the base hostname & protocol for your site
twitter_username: karan301_

# Build settings
markdown: kramdown

permalink: /:title